from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView
from .views import *

urlpatterns = [
    path('login/', include('django.contrib.auth.urls')),
    path('login/', LoginUser.as_view(), name='login'),
    path('registration/', SignUpView.as_view(), name='registration'),
    path('staff_registration/', SignUpStaff.as_view(), name='staff_registration'),
    path('', profile, name='profile'),
    path('news/', news, name='news'),
    path('news/<int:news_id>/', view_news, name='view_news'),
    path('create_order/', create_order, name='create_order'),
    path('orders/', orders, name='orders'),
    path('orders/delete_order/<int:pk>', DeleteOrder.as_view(), name='delete_order'),
    path('orders_admin', orders_admin, name='orders_admin'),
    path('orders_admin/pay', orders_admin_pay, name='orders_pay'),
    path('orders_admin/way', orders_admin_way, name='orders_admin_way'),
    path('orders_admin/del', orders_admin_del, name='orders_admin_del'),
    path('statistic/', stat, name='statistic'),
    path('statistic_admin/', create_statistic, name='statistic_admin'),
    path('statistic_admin/<int:group_id>/', get_group_stat, name='group_stat'),
    path('create_news/', create_news, name='create_news'),
    path('sportsmen/', sportsmen, name='sportsmen'),
    path('sportsmen/create', create_sportsman, name='create_sportsman'),
    path('sportsmen/group/<int:group_id>/', sportsmen_group, name='sportsmen_group'),
    path('sportsmen/filial/<int:filial_id>/', sportsmen_filial, name='sportsmen_filial'),
    path('sportsmen/<int:pk>', SportsmenUpdate.as_view(), name='sportsmen_update'),
    path('sportsmen/delete/<int:pk>', DeleteSportsman.as_view(), name='delete_sportsman'),
    path('groups/', groups, name='groups'),
    path('filial/<int:filial_id>', filials, name='filial'),
    path('filial/new', FilialCreate.as_view(), name='create_filial'),
    path('filial/update/<int:pk>', FilialUpdate.as_view(), name='filial_update'),
    # path('groups/new', CreateGroup.as_view(), name='create_group'),
    path('groups/new/<int:filial_id>', create_group, name='create_group'),
    path('groups/<int:pk>', GroupUpdate.as_view(), name='group_update'),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.png'), name='favicon'),
    path('ajax/load-clubs/', load_clubs, name='ajax_load_clubs'),
    path('ajax/load-groups/', load_groups, name='ajax_load_groups'),
    path('certificates/', cert_active, name='cert_active'),
    path('certificates/all', cert_all, name='cert_all'),
    path('certificates/update/<int:pk>', CertUpdate.as_view(), name='cert_update'),
    path('certificates/create', CertCreate.as_view(), name='cert_create'),
    path('personal/', personal, name='personal'),
    path('personal/trainers', personal_trainers, name='personal_trainers'),
    path('personal/admins', personal_admins, name='personal_admins'),
    path('personal/new', create_personal, name='personal_create'),

]