# Generated by Django 3.2.4 on 2021-08-01 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Город')),
                ('region', models.CharField(max_length=80, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Клуб', 'verbose_name_plural': 'Клубы'},
        ),
        migrations.RemoveField(
            model_name='filial',
            name='city',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_f',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_f',
        ),
        migrations.AddField(
            model_name='filial',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='LK.club', verbose_name='Клуб'),
        ),
        migrations.AddField(
            model_name='filial',
            name='payment',
            field=models.IntegerField(null=True, verbose_name='Стоимость аренды'),
        ),
        migrations.AddField(
            model_name='filial',
            name='type_of_pay',
            field=models.CharField(choices=[('Час', 'Почасовая'), ('Мес', 'Ежемесячная')], default='Час', max_length=3, verbose_name='Вид аренды'),
        ),
        migrations.AddField(
            model_name='trainers',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер паспорта спортсмена'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес спортсмена'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='belt',
            field=models.CharField(max_length=10, null=True, verbose_name='Пояс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_m',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя родителя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_m',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия родителя'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('category', models.CharField(max_length=30, verbose_name='Категории')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время публикации')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LK.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_numb', models.CharField(max_length=30, verbose_name='Номер сертификата')),
                ('status', models.CharField(choices=[('Дейст', 'Действующий'), ('НеДейств', 'Не действующий')], default='Дейст', max_length=8, verbose_name='Статус')),
                ('data', models.DateField(verbose_name='Дата выдачи')),
                ('belt', models.CharField(max_length=50, verbose_name='Пояс')),
                ('color', models.CharField(max_length=60, null=True, verbose_name='Цвет')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LK.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='belt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='LK.certificates', verbose_name='Сертификат'),
        ),
        migrations.DeleteModel(
            name='Belt',
        ),
    ]
