# Generated by Django 3.2.4 on 2021-08-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='job',
            field=models.CharField(choices=[('Инстр', 'Инструктор'), ('РукКл', 'Руководитель клуба'), ('РукФл', 'Руководитель филиала'), ('Помощ', 'Помощник')], default='Инстр', max_length=5, verbose_name='Должность'),
        ),
    ]
