# Generated by Django 3.2.4 on 2021-08-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0006_trainers_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='belt',
        ),
    ]
