# Generated by Django 3.2.4 on 2021-08-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0007_remove_user_belt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Статус'),
        ),
    ]
