# Generated by Django 3.2.4 on 2021-08-07 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0009_auto_20210806_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('size', models.CharField(max_length=30, verbose_name='Размер')),
                ('status', models.CharField(choices=[('Ожидает оплаты', 'Ожидает оплаты'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], default='Ожидает оплаты', max_length=15, verbose_name='Статус заказа')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='Цвет')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
