# Generated by Django 3.2.4 on 2021-08-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0010_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ожидает оплаты', 'Ожидает оплаты'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], default='Ожидает оплаты', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
