# Generated by Django 3.2.4 on 2021-08-08 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0011_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='color',
            field=models.CharField(blank=True, choices=[('Красный', 'Красный'), ('Синий', 'Синий')], default='Белый', max_length=40, verbose_name='Цвет'),
        ),
    ]
