# Generated by Django 3.2.4 on 2021-08-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LK', '0012_auto_20210808_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='color',
            field=models.CharField(blank=True, choices=[('Синий', 'Синий'), ('Красный', 'Красный'), ('Желтый', 'Желтый'), ('Зеленый', 'Зеленый'), ('Белый', 'Белый'), ('Черный', 'Черный')], default='Красный', max_length=40, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.CharField(blank=True, choices=[('100', '100'), ('110', '110'), ('120', '120'), ('130', '130'), ('140', '140'), ('150', '150'), ('160', '160'), ('170', '170'), ('180', '180'), ('190', '190'), ('200', '200'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=30, null=True, verbose_name='Размер'),
        ),
    ]
